### PR TITLE
Feature/anchor links per test

### PR DESCRIPTION
**Pull request by nikcorg**
Adds anchor links for each test for convenient deep linkability.

NB. couldn't get the local generation running (just get an empty prompt asking about which stage to run), which means this is untested code, but it should be ok...

this-is-fine

### CODE REVIEW

**Comment by jonknapp** [comment]
💯 awesome! I'll look over things when I get some time after the conference and bring this in if there are no issues.

**Comment by nikcorg** [comment]
Hey @jonknapp,

I'm happy to address any issues with this PR, if that's what's keeping it in its dormant state.

/n

**Comment by jonknapp** [comment]
Hi @nikcorg, it's not you, it's me.  😄  I'm anxiously awaiting the birth of my first son and project work has been more plentiful than I would have liked at this time. It's still on my radar, but I haven't been able to address it yet.

**Comment by nikcorg** [comment]
Hehe, no worries. I expected it to be something like that, but figured I'd give it a little nudge, in case you're like me and simply forget things. Congrats on your imminently arriving firstborn :-)

**Comment by jonknapp** [comment]
Code pulled in and released on whatdoeslambdasupport.com! Thanks again for the PR and for waiting for me to get to it.

**Comment by nikcorg** [comment]
My pleasure :-)

**Pull request merged**
